permit_join: true
mqtt:
  base_topic: 5gdrone/heart/zigbee2mqtt
  server: mqtt://mqtt
serial:
  port: /dev/ttyACM0
  adapter: ezsp
frontend:
  port: 8080
advanced:
  network_key:
    - 245
    - 167
    - 70
    - 227
    - 149
    - 130
    - 95
    - 203
    - 150
    - 56
    - 144
    - 32
    - 54
    - 171
    - 8
    - 69
devices:
  '0x001788010cd9261b':
    friendly_name: '0x001788010cd9261b'
