permit_join: true
mqtt:
  base_topic: 5gdrone/heart/zigbee2mqtt
  server: mqtt://mqtt
serial:
  port: /dev/ttyACM0
  adapter: ezsp
frontend:
  port: 8080
advanced:
  network_key:
    - 132
    - 204
    - 66
    - 80
    - 206
    - 8
    - 224
    - 180
    - 213
    - 25
    - 169
    - 210
    - 208
    - 47
    - 127
    - 118
devices:
  '0x001788010cd9261b':
    friendly_name: '0x001788010cd9261b'
